//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pms.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Camera
    {
        public long CameraId { get; set; }
        public string CameraName { get; set; }
        public long RelatedParkingId { get; set; }
        public string SecurityKey { get; set; }
    
        public virtual Parking Parking { get; set; }
    }
}
