//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pms.Data.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Parking
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Parking()
        {
            this.Cameras = new HashSet<Camera>();
        }
    
        public long ParkingID { get; set; }
        public string ParkingName { get; set; }
        public Nullable<long> TotalSlots { get; set; }
        public Nullable<long> SlotsUnderMaintenance { get; set; }
        public Nullable<long> SlotsOccupied { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Camera> Cameras { get; set; }
    }
}
